# Generated by Django 3.2.5 on 2021-10-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_team_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_no']},
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('track', 'question_no')},
        ),
    ]
