# Generated by Django 3.2.5 on 2021-10-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20211015_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='given_answer',
        ),
    ]
