# Generated by Django 3.2.5 on 2021-10-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_rename_answer_answer_given_answer'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='team',
            managers=[
            ],
        ),
    ]
