# Generated by Django 3.2.5 on 2021-11-07 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_alter_team_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='super_hint',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='UsedHints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedhints', to='quizapp.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedhints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'team')},
            },
        ),
    ]
